#!/bin/sh

DEBUG=1 UCOME='druby://127.0.0.1:9007' MONGO='mongodb://localhost/ucome' ./ucome.rb &

DEBUG=1 UCOME='druby://127.0.0.1:9007' ./acome.rb &

ps ax | egrep '[i]come.rb' >/dev/null
if [ "$?" -eq 0 ]; then
    echo "icome はすでに起動しています。"
else
    DEBUG=1 UCOME='druby://127.0.0.1:9007' ./icome.rb &
fi

