#!/bin/sh

ps ax | egrep '[i]come.rb' >/dev/null
if [ "$?" -eq 0 ]; then
    echo "icome はすでに起動しています。"
    exit
fi

ICOME=/edu/lib/icome8/icome.rb
if [ $# -neq 0 ]; then
    DEBUG=1 UCOME='druby://127.0.0.1:9007' ${ICOME} $@
    exit
fi
echo "icome の起動には 5 秒くらいかかります。"
UCOME='druby://150.69.90.81:9007' nohup ${ICOME} 2>/dev/null &

if [ -e /edu/bin/watch-ss ]; then
    nohup /edu/bin/watch-ss 2>/dev/null &
fi
