#!/bin/sh
# icome launch script for isc.

ps ax | egrep '[i]come.rb' >/dev/null
if [ "$?" -eq 0 ]; then
    echo icome はすでに起動しています。
    exit
fi
echo icome の起動には 5 秒くらいかかります。

if [ -f /home/t/hkimura/icome8/icome.rb ]; then
    echo "isc icome"
    ICOME=/home/t/hkimura/icome8/icome.rb
    UCOME='druby://150.69.90.82:9007' ${ICOME}
else
    echo "debug icome"
    DEBUG=1 ./icome.rb
fi

# 2017-03-12, この nohup の意味は？
#if [ -e /edu/bin/xwatch-ss ]; then
#    echo "xwatch-ss"
#    /edu/bin/xwatch-ss 2>/dev/null &
#fi
