#!/bin/sh
if [ $# -eq 0 ]; then
    MONGO='mongodb://dbs.melt.kyutech.ac.jp/ucome' \
         UCOME='druby://150.69.90.81:9007' ./ucome.rb
else
    DEBUG=1 MONGO='mongodb://dbs.melt.kyutech.ac.jp/test' \
         UCOME='druby://127.0.0.1:9007' ./ucome.rb $@
fi
